site_name: "Ac's Notes"
site_url: https://acxikaly.top/note/
repo_name: accclarkson177-svg/note
repo_url: https://github.com/accclarkson177-svg/note
edit_uri: tree/master/docs
site_description: "Ac's Notes"
copyright: Copyright &copy; 2026 <a href="https://github.com/accclarkson177-svg" target="_blank" rel="noopener">Ac</a>

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  static_templates:
    - redirection.html  
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.top
    - navigation.tabs   
    - navigation.footer
    #- navigation.indexes
  font: false
  palette:
    - scheme: default


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
    

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/accclarkson177-svg/note
    - icon: fontawesome/solid/home
      link: https://acxikaly.top
  analytics:
    provider: custom
    property: G-DYETCPM289

extra_css:
  # 1. 霞鹜文楷 (网页屏幕版) - 免费公共 CDN
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  # 2. JetBrains Mono (极客代码字体) - 免费公共 CDN
  - https://cdn.jsdelivr.net/npm/jetbrains-mono@1.0.6/css/jetbrains-mono.css
  # 3. 如果他用了 Katex 公式库，也顺手换成公共的，免得以后公式也裂开
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - css/tasklist.css
  - css/custom.css
  - css/card.css
  - css/flink.css
  - css/changelog_extra.css
  - css/toc_extra.css
  - css/svg_extra.css

  



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js

plugins:
  - rss:
      enabled: !ENV [FULL, false]
  - search
  - glightbox:
      width: 80%
  - encryptcontent:  # now just for one page, need to be improved
      title_prefix: "🔒 "
      remember_password: True 
      default_expire_dalay: 48
      decryption_failure_message: '密码错误'
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
  #- git-revision-date-localized:
  #enabled: !ENV [FULL, false]
  #type: datetime
  #timezone: Asia/Shanghai
  #locale: zh
  #enable_creation_date: true
  #enable_git_follow: true
  #ignored_commits_file: .ignored-commits
  #exclude:
  #  - index.md
  #  - writeups/AAA.md
  #- changelog
  - statistics:
      page_check_metadata: comment
  - heti:
      enabled: !ENV [FULL, false]
      disable_serve: false

hooks:
 - hooks/theme_override.py
 - hooks/linkbackward.py
 - hooks/toc.py
 
not_in_nav: |
  todo.md
  cs/algorithm/ds-som/index.md

nav:
  - WELCOME:
      - Home: index.md
      - 更新记录: changelog.md
      - 友链: links.md
  - 高中:
      - 笔记:
          - 首页: highschool/home.md
          - 语文: highschool/ch/index.md
          - 数学: highschool/ma/index.md
  - AI使用:
      - 工具分析: aires/tools.md  
      - Prompt积累: aires/prompt.md
      - 大佬的提示词: aires/prompt_g.md
  
  - 🎼乐谱库: 
    - 曲谱展厅: sheet_music/index.md
    - 曲目简介:
      - City of Stars: sheet_music/cityofstars.md
      - Cadenza for 月半小夜曲: sheet_music/ybxyq.md
  - Others:
      - others/index.md
# 比如数学好题整理，然后可以比如上次线代作业那个归纳法和我说的那个高考题目不等式的题型归纳到一起，或者说一些好题的总结之类的
     